name: nft_creator
description: An NFT creator and wallet app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+3

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  flutter_lints: ^2.0.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.0.8
  flutter_colorpicker: ^1.0.3
  on_image_matrix: ^1.0.0+1
  image: ^4.0.15
  delayed_display: ^2.0.0
  anitex: ^2.0.0
  assets_audio_player: ^3.0.3+6
  rflutter_alert: ^2.0.4
  lottie: ^1.2.0
  replay_bloc: ^0.2.3
  flutter_bloc: ^8.1.2
  image_picker: ^0.8.6+2
  flutter_speed_dial: ^6.2.0
  path_provider: ^2.0.12
  intl: ^0.18.0
  sqflite: ^2.2.2
  image_gallery_saver: ^1.7.1
  screenshot: ^1.3.0
  telegram: ^0.0.3
  http: ^0.13.5
  infinite_scroll_pagination: ^3.2.0
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/
    - assets/lottie/
  fonts:
    - family: solata-extrabold
      fonts:
        - asset: assets/fonts/solata-extrabold.ttf
    - family: solata-bold
      fonts:
        - asset: assets/fonts/solata-bold.ttf
    - family: solata-semibold
      fonts:
        - asset: assets/fonts/solata-semibold.ttf
    - family: solata-medium
      fonts:
        - asset: assets/fonts/solata-medium.ttf
    - family: solata-regular
      fonts:
        - asset: assets/fonts/solata-regular.ttf
    - family: Carter
      fonts:
        - asset: assets/fonts/CarterOne-Regular.ttf
    - family: Coiny-Regular
      fonts:
        - asset: assets/fonts/Coiny-Regular.ttf
    - family: Paytone
      fonts:
        - asset: assets/fonts/PaytoneOne-Regular.ttf